# Generated by Django 2.2.6 on 2019-10-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlpId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slp_id', models.CharField(editable=False, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('public_key', models.CharField(editable=False, max_length=44)),
                ('private_key', models.CharField(editable=False, max_length=44)),
                ('received_public_key', models.CharField(editable=False, max_length=44)),
                ('received_private_key', models.CharField(editable=False, max_length=44)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slp_id')},
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(default=None, max_length=100, unique=True)),
                ('value', models.CharField(default=None, max_length=100)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(unique=True)),
                ('ledger_asset', models.CharField(default=None, editable=False, max_length=100)),
                ('recipient', models.CharField(default=None, editable=False, max_length=44)),
                ('tx_type', models.CharField(default=None, editable=False, max_length=8)),
                ('slp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.SlpId')),
            ],
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=44)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'alias')},
            },
        ),
    ]
